# name: Generate Quiz Bank List

# on:
#   push:
#     branches:
#       - main

# jobs:
#   generate-list:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'

#       - name: Generate quiz bank list
#         run: node utils/geneart_bank_list.js

#       - name: Commit and push if changed
#         run: |
#           git config --global user.name 'GitHub Actions Bot'
#           git config --global user.email 'actions@github.com'
#           git add assets/list.json
#           git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate quiz bank list" && git push) 